# Encoded cluster name is outbound|8080|grpc|extensionserver.default.svc.cluster.local
apiVersion: v1
kind: ConfigMap
metadata:
  name: extensionserver
data:
  extension.yaml: |
    extensions:
    - name: demo
      url: https://storage.googleapis.com/istio-build/proxy/headers_rust.wasm
      sha256: 51c05f21fd857db613120220f12b282042ca60bc7a9813b63b79eab0b0347505
      runtime: v8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extensionserver
  labels:
    app: extensionserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extensionserver
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: extensionserver
    spec:
      containers:
      - name: extensionserver
        image: gcr.io/istio-testing/extensionserver:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/extensionserver/config
      volumes:
      - name: config
        configMap:
          name: extensionserver
---
apiVersion: v1
kind: Service
metadata:
  name: extensionserver
spec:
  selector:
    app: extensionserver
  ports:
    - protocol: TCP
      port: 8080
      name: grpc
---
