version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
    - checkout
    - run: >-
        docker run \
          --privileged \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd):/work/ \
          -w /work/ \
          gcr.io/istio-testing/build-tools:master-2020-03-18T15-19-34 \
          bash -c 'make build'
    - store_artifacts:
        path: /work/bazel-bin/src/envoy/envoy

workflows:
  version: 2
  all:
    jobs:
      - build
